<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://www.example.org/ns/porder" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://oracle.com/sca/soapservice/Basic/HelloWorld/ReceiveData"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/file/Basic/HelloWorld/WriteData"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ReceiveData.wsdl"/>
            <oracle-xsl-mapper:rootElement name="PurchaseOrder" namespace="http://www.example.org/ns/porder"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/WriteData.wsdl"/>
            <oracle-xsl-mapper:rootElement name="PurchaseOrder" namespace="http://www.example.org/ns/porder"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [THU AUG 29 14:27:35 EDT 2019].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:PurchaseOrder>
         <ns0:custID>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:custID"/>
         </ns0:custID>
         <ns0:ID>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:ID"/>
         </ns0:ID>
         <ns0:payOption>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:payOption"/>
         </ns0:payOption>
         <ns0:shipChoice>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:shipChoice"/>
         </ns0:shipChoice>
         <ns0:status>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:status"/>
         </ns0:status>
         <xsl:if test="/ns0:PurchaseOrder/ns0:ccType">
            <ns0:ccType>
               <xsl:value-of select="/ns0:PurchaseOrder/ns0:ccType"/>
            </ns0:ccType>
         </xsl:if>
         <xsl:if test="/ns0:PurchaseOrder/ns0:ccNumber">
            <ns0:ccNumber>
               <xsl:value-of select="/ns0:PurchaseOrder/ns0:ccNumber"/>
            </ns0:ccNumber>
         </xsl:if>
         <ns0:items>
            <xsl:for-each select="/ns0:PurchaseOrder/ns0:items/ns0:item">
               <ns0:item>
                  <ns0:productId>
                     <xsl:value-of select="ns0:productId"/>
                  </ns0:productId>
                  <ns0:productName>
                     <xsl:value-of select="ns0:productName"/>
                  </ns0:productName>
                  <ns0:price>
                     <xsl:value-of select="ns0:price"/>
                  </ns0:price>
                  <ns0:quantity>
                     <xsl:value-of select="ns0:quantity"/>
                  </ns0:quantity>
               </ns0:item>
            </xsl:for-each>
         </ns0:items>
      </ns0:PurchaseOrder>
   </xsl:template>
</xsl:stylesheet>
